---
name: Alchemy
version: 1.0.0
config-version: 2
profile: default
source-paths:
- models
analysis-paths:
- analysis
test-paths:
- tests
data-paths:
- data
macro-paths:
- macros
snapshot-paths:
- snapshots
target-path: target
clean-targets:
- target
- dbt_modules
vars:
  asana_source:
    asana_schema: fivetran_asana
  fivetran_log:
    fivetran_log_schema: fivetran_log
    fivetran_log_using_transformations: false
    fivetran_log_using_triggers: false
  hubspot_source:
    hubspot_schema: fivetran_hubspot
  quickbooks_source:
    quickbooks_schema: fivetran_quickbooks
  stripe_source:
    stripe_schema: fivetran_stripe
    using_invoices: false
    using_payment_method: false
    using_subscriptions: false
models:
