---
dbtVersion: 0.18.1
jobs:
- name: '01'
  schedule: 0 0 00 1/1 * ? *
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run fivetran log
    command: |
      dbt run --models fivetran_log --vars ---
      vars:
        fivetran_log:
          fivetran_log_schema: fivetran_log_schema
          fivetran_log_using_transformations: false
          fivetran_log_using_triggers: true
  - name: run asana
    command: |
      dbt run --models asana --vars ---
      vars:
        asana_source:
          asana_schema: just_asana_schema
          is_active: true
      models:
        asana_source:
          materialized: table
