---
dbtVersion: 0.18.1
jobs:
- name: test
  schedule: "* * * * *"
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run asana
    command: dbt run --models asana
- name: aaa
  schedule: "* * * * * "
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run fivetran log
    command: dbt run --models fivetran_log
