---
dbtVersion: 0.18.1
jobs:
- name: '2'
  schedule: "* * * * *"
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run asana
    command: dbt run --models asana
  - name: run fivetran log
    command: dbt run --models fivetran_log
  - name: run github
    command: dbt run --models github
  - name: run google ads
    command: dbt run --models google_ads
  - name: run hubspot
    command: dbt run --models hubspot
- name: '1'
  schedule: "* * * * *"
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run asana
    command: dbt run --models asana
  - name: run fivetran log
    command: dbt run --models fivetran_log
  - name: run github
    command: dbt run --models github
  - name: run google ads
    command: dbt run --models google_ads
  - name: run hubspot
    command: dbt run --models hubspot
