---
dbtVersion: 0.18.1
jobs:
- name: '1'
  schedule: "* * * * *"
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run Zendesk Support
    command: dbt run --models fivetran/zendesk
  - name: run Salesforce
    command: dbt run --models fivetran/salesforce
  - name: run Shopify
    command: dbt run --models fivetran/shopify
  - name: run Stripe
    command: dbt run --models fivetran/stripe
  - name: run Twitter Ads
    command: dbt run --models fivetran/twitter_ads
- name: '2'
  schedule: "* * * * *"
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run Salesforce
    command: dbt run --models fivetran/salesforce
  - name: run Shopify
    command: dbt run --models fivetran/shopify
  - name: run Stripe
    command: dbt run --models fivetran/stripe
  - name: run Twitter Ads
    command: dbt run --models fivetran/twitter_ads
  - name: run Zendesk Support
    command: dbt run --models fivetran/zendesk
