---
dbtVersion: 0.18.1
jobs:
- name: '1'
  schedule: "* * * * * "
  steps:
  - name: version
    command: dbt --version
- name: '2'
  schedule: "* * * * *"
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run github
    command: dbt run --models github
  - name: run hubspot
    command: dbt run --models hubspot
  - name: run google ads
    command: dbt run --models google_ads
  - name: run intercom
    command: dbt run --models intercom
  - name: run jira
    command: dbt run --models jira
