---
dbtVersion: 0.18.1
jobs:
- name: '01'
  schedule: 0 0 00 1/1 * ? *
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run asana
    command: dbt run --models asana
  - name: run fivetran log
    command: dbt run --models fivetran_log
- name: '02'
  schedule: 0 0 00 1/1 * ? *
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run asana
    command: dbt run --models asana
