---
dbtVersion: 0.18.1
jobs:
- name: test
  schedule: "* * * * *"
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run asana
    command: dbt run --models asana
  - name: run github
    command: dbt run --models github
