---
dbtVersion: 0.18.1
jobs:
- name: '02'
  schedule: 0 0 00 1/1 * ?
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run asana
    command: dbt run --models asana --vars '{"asana_source":{"asana_schema":"fivetran_asana","is_active":true}}'
  - name: run stripe
    command: dbt run --models stripe --vars '{"stripe_source":{"stripe_schema":"stripe_schema","using_invoices":true,"using_payment_method":true,"using_subscriptions":true}}'
