---
dbtVersion: 0.18.1
jobs:
- name: '1'
  schedule: "* * * * *"
  steps:
  - name: version
    command: dbt --version
  - name: Zendesk Support
    command: dbt run --models fivetran/zendesk
  - name: Salesforce
    command: dbt run --models fivetran/salesforce
  - name: Shopify
    command: dbt run --models fivetran/shopify
  - name: Stripe
    command: dbt run --models fivetran/stripe
  - name: Twitter Ads
    command: dbt run --models fivetran/twitter_ads
