---
dbtVersion: 0.18.1
jobs:
- name: '02'
  schedule: 0 0 00 1/1 * ?
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run asana
    command: dbt run --models asana --vars '{"asana_source":{"asana_schema":"fivetran_asana","is_active":true}}'
  - name: run stripe
    command: dbt run --models stripe --vars '{"stripe_source":{"stripe_schema":"stripe_schema_111","using_invoices":true,"using_payment_method":true,"using_subscriptions":true}}'
  - name: run quickbooks
    command: dbt run --models quickbooks --vars '{"quickbooks_source":{"quickbooks_schema":"123123123"}}'
- name: '01'
  schedule: 0 16 16 1/3 * ?
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run fivetran log
    command: dbt run --models fivetran_log --vars '{"fivetran_log":{"fivetran_log_schema":"fivetran_log_schema","fivetran_log_using_transformations":false,"fivetran_log_using_triggers":true}}'
  - name: run asana
    command: dbt run --models asana --vars '{"asana_source":{"asana_schema":"just_asana_schema","is_active":true}}'
