---
dbtVersion: 0.18.1
jobs:
- name: test
  schedule: "* * * * *"
  steps:
  - name: version
    command: dbt --version
- name: aaa
  schedule: "* * * * * "
  steps:
  - name: version
    command: dbt --version
