---
dbtVersion: 0.18.1
jobs:
- name: '1'
  schedule: "* * * * *"
  steps:
  - name: version
    command: dbt --version
  - name: run zendesk support
    command: dbt run --models fivetran/zendesk
  - name: run salesforce
    command: dbt run --models fivetran/salesforce
  - name: run shopify
    command: dbt run --models fivetran/shopify
  - name: run stripe
    command: dbt run --models fivetran/stripe
  - name: run twitter ads
    command: dbt run --models fivetran/twitter_ads
