---
dbtVersion: 0.18.1
jobs:
- name: '1'
  schedule: 0 0 00 1 1/1 ?
  steps:
  - name: version
    command: dbt --version
- name: '2'
  schedule: "* * * * *"
  steps:
  - name: version
    command: dbt --version
